// ============================================================================
// petlo - Schedules Repository
// ============================================================================
//
// 予定 (build 5) の CRUD。
// pets.birthday から自動生成される schedule の管理もここに集約。
//
// ============================================================================

import 'dart:convert';

import 'package:drift/drift.dart';

import '../local/app_database.dart';
import '../local/database_enums.dart';
import 'base_repository.dart';

class SchedulesRepository extends BaseRepository {
  SchedulesRepository(super.db);

  // ============================================================================
  // Read
  // ============================================================================

  /// グループ内の有効スケジュール(scheduledAt 昇順)
  Stream<List<ScheduleEntity>> watchForGroup(String groupId, {int? limit}) {
    final query = db.select(db.schedules)
      ..where((Schedules t) =>
          t.groupId.equals(groupId) & t.deletedAt.isNull())
      ..orderBy(<OrderClauseGenerator<Schedules>>[
        (Schedules t) => OrderingTerm(expression: t.scheduledAt),
      ]);
    if (limit != null) query.limit(limit);
    return query.watch();
  }

  /// 期間内のスケジュール(カレンダー表示用)
  Stream<List<ScheduleEntity>> watchInRange({
    required String groupId,
    required int fromMsec,
    required int toMsec,
  }) {
    return (db.select(db.schedules)
          ..where((Schedules t) =>
              t.groupId.equals(groupId) &
              t.deletedAt.isNull() &
              t.scheduledAt.isBetweenValues(fromMsec, toMsec))
          ..orderBy(<OrderClauseGenerator<Schedules>>[
            (Schedules t) => OrderingTerm(expression: t.scheduledAt),
          ]))
        .watch();
  }

  Future<ScheduleEntity?> getById(int id) {
    return (db.select(db.schedules)
          ..where((Schedules t) => t.id.equals(id))
          ..limit(1))
        .getSingleOrNull();
  }

  /// 起動時の再スケジュール対象を返す。
  /// - deleted_at IS NULL
  /// - times が立っている (= 繰り返し通知あり)、または
  ///   notificationTiming != 'none' かつ scheduledAt が未来
  ///   のどちらか
  ///
  /// scheduledAt 昇順 (近い予定から優先して slot 予算を消費する)。
  /// build 47b (Scope B3).
  Future<List<ScheduleEntity>> getAllForRescheduling() async {
    final int now = DateTime.now().millisecondsSinceEpoch;
    final query = db.select(db.schedules)
      ..where((Schedules t) =>
          t.deletedAt.isNull() &
          (t.times.isNotNull() |
              (t.notificationTiming.equals('none').not() &
                  t.scheduledAt.isBiggerOrEqualValue(now))))
      ..orderBy(<OrderClauseGenerator<Schedules>>[
        (Schedules t) => OrderingTerm(expression: t.scheduledAt),
      ]);
    return query.get();
  }

  /// ペット birthday の自動 schedule を1件返す(なければ null)
  Future<ScheduleEntity?> getAutoBirthdayForPet(int petId) {
    return (db.select(db.schedules)
          ..where((Schedules t) =>
              t.deletedAt.isNull() &
              t.sourcePetId.equals(petId) &
              t.sourceType.equals(ScheduleSourceType.pet_birthday.name))
          ..limit(1))
        .getSingleOrNull();
  }

  // ============================================================================
  // Write
  // ============================================================================

  Future<int> create({
    required String groupId,
    required String title,
    required ScheduleCategory category,
    required int scheduledAtMsec,
    bool hasTime = false,
    ScheduleRecurrence recurrence = ScheduleRecurrence.none,
    ScheduleNotificationTiming notificationTiming =
        ScheduleNotificationTiming.none,
    String? notes,
    List<int>? relatedPetIds,
    bool isAutoGenerated = false,
    ScheduleSourceType sourceType = ScheduleSourceType.manual,
    int? sourcePetId,
    String? createdBy,
    // build 47b (Scope B1+B4): medication カテゴリ向け繰り返し通知パラメタ。
    // category != medication なら無視される。
    List<String>? times,
    Set<int>? weekdays,
  }) async {
    final String trimmedTitle = title.trim();
    if (trimmedTitle.isEmpty) {
      throw ArgumentError('title cannot be empty');
    }
    final meta = buildCreateMetadata(groupId: groupId);

    final bool isMedication = category == ScheduleCategory.medication;
    final String? timesEncoded = (isMedication &&
            times != null &&
            times.isNotEmpty)
        ? jsonEncode(times)
        : null;
    final int? weekdaysBits = (isMedication &&
            weekdays != null &&
            weekdays.isNotEmpty)
        ? _encodeWeekdays(weekdays)
        : null;

    final int newId = await db.into(db.schedules).insert(
          SchedulesCompanion.insert(
            groupId: Value(groupId),
            title: trimmedTitle,
            category: category,
            scheduledAt: scheduledAtMsec,
            hasTime: Value(hasTime),
            recurrence: Value(recurrence),
            notificationTiming: Value(notificationTiming),
            notes: Value(_emptyToNull(notes)),
            relatedPetIds: Value(
              (relatedPetIds ?? <int>[])
                  .map((int i) => i.toString())
                  .toList(),
            ),
            isAutoGenerated: Value(isAutoGenerated),
            sourceType: Value(sourceType),
            sourcePetId: Value(sourcePetId),
            createdBy: Value(createdBy),
            syncStatus: Value(meta.initialSyncStatus),
            createdAt: meta.createdAt,
            updatedAt: meta.updatedAt,
            lastModifiedAtClient: Value(meta.lastModifiedAtClient),
            times: Value(timesEncoded),
            weekdaysBits: Value(weekdaysBits),
          ),
        );

    await enqueueSyncIfShared(
      groupId: groupId,
      operation: SyncOperation.insert,
      targetTable: 'schedules',
      recordId: newId,
      payloadJson: jsonEncode(<String, dynamic>{
        'title': trimmedTitle,
        'category': category.name,
        'scheduledAt': scheduledAtMsec,
      }),
    );
    return newId;
  }

  Future<bool> update({
    required int scheduleId,
    String? title,
    ScheduleCategory? category,
    int? scheduledAtMsec,
    bool? hasTime,
    ScheduleRecurrence? recurrence,
    ScheduleNotificationTiming? notificationTiming,
    String? notes,
    bool clearNotes = false,
    List<int>? relatedPetIds,
    // build 47b (Scope B1+B4): medication 用パラメタ。
    // clearMedicationFields=true で明示的に times/weekdays を null に戻す
    // (category=medication から別カテゴリに切り替えた時など)。
    List<String>? times,
    Set<int>? weekdays,
    bool clearMedicationFields = false,
  }) async {
    final ScheduleEntity? existing = await getById(scheduleId);
    if (existing == null) throw StateError('Schedule not found: id=$scheduleId');

    if (title != null && title.trim().isEmpty) {
      throw ArgumentError('title cannot be empty');
    }

    final meta = buildUpdateMetadata(groupId: existing.groupId);

    Value<String?> timesValue = const Value.absent();
    Value<int?> weekdaysValue = const Value.absent();
    if (clearMedicationFields) {
      timesValue = const Value<String?>(null);
      weekdaysValue = const Value<int?>(null);
    } else {
      if (times != null) {
        timesValue =
            Value<String?>(times.isEmpty ? null : jsonEncode(times));
      }
      if (weekdays != null) {
        weekdaysValue =
            Value<int?>(weekdays.isEmpty ? null : _encodeWeekdays(weekdays));
      }
    }

    final companion = SchedulesCompanion(
      title: title == null ? const Value.absent() : Value(title.trim()),
      category:
          category == null ? const Value.absent() : Value(category),
      scheduledAt: scheduledAtMsec == null
          ? const Value.absent()
          : Value(scheduledAtMsec),
      hasTime: hasTime == null ? const Value.absent() : Value(hasTime),
      recurrence:
          recurrence == null ? const Value.absent() : Value(recurrence),
      notificationTiming: notificationTiming == null
          ? const Value.absent()
          : Value(notificationTiming),
      notes: clearNotes
          ? const Value(null)
          : (notes == null
              ? const Value.absent()
              : Value(_emptyToNull(notes))),
      relatedPetIds: relatedPetIds == null
          ? const Value.absent()
          : Value(relatedPetIds.map((int i) => i.toString()).toList()),
      syncStatus: Value(meta.updatedSyncStatus),
      updatedAt: Value(meta.updatedAt),
      lastModifiedAtClient: Value(meta.lastModifiedAtClient),
      times: timesValue,
      weekdaysBits: weekdaysValue,
    );

    final int affected = await (db.update(db.schedules)
          ..where((Schedules t) => t.id.equals(scheduleId)))
        .write(companion);

    if (affected > 0) {
      await enqueueSyncIfShared(
        groupId: existing.groupId,
        operation: SyncOperation.update,
        targetTable: 'schedules',
        recordId: scheduleId,
        payloadJson: jsonEncode(<String, dynamic>{}),
      );
    }
    return affected > 0;
  }

  Future<bool> softDelete(int scheduleId) async {
    final ScheduleEntity? existing = await getById(scheduleId);
    if (existing == null) return false;

    final meta = buildDeleteMetadata(groupId: existing.groupId);
    final int affected = await (db.update(db.schedules)
          ..where((Schedules t) => t.id.equals(scheduleId)))
        .write(SchedulesCompanion(
      deletedAt: Value(meta.deletedAt),
      syncStatus: Value(meta.updatedSyncStatus),
      updatedAt: Value(meta.updatedAt),
      lastModifiedAtClient: Value(meta.lastModifiedAtClient),
    ));

    if (affected > 0) {
      await enqueueSyncIfShared(
        groupId: existing.groupId,
        operation: SyncOperation.delete,
        targetTable: 'schedules',
        recordId: scheduleId,
        payloadJson: jsonEncode(<String, dynamic>{}),
      );
    }
    return affected > 0;
  }

  // ============================================================================
  // 自動生成 (ペット birthday)
  // ============================================================================

  /// ペットの birthday から auto schedule を作成または更新する。
  /// - birthday が null なら既存の auto schedule を soft delete。
  /// - 既に存在すれば日付・タイトルを更新。
  /// - なければ新規作成。
  Future<void> upsertBirthdaySchedule({
    required String groupId,
    required int petId,
    required String petName,
    required int? birthdayMsec,
    required String birthdaySuffix,
  }) async {
    final ScheduleEntity? existing = await getAutoBirthdayForPet(petId);

    if (birthdayMsec == null) {
      if (existing != null) {
        await softDelete(existing.id);
      }
      return;
    }

    final String title = '$petName$birthdaySuffix';

    if (existing == null) {
      await create(
        groupId: groupId,
        title: title,
        category: ScheduleCategory.birthday,
        scheduledAtMsec: birthdayMsec,
        recurrence: ScheduleRecurrence.yearly,
        relatedPetIds: <int>[petId],
        isAutoGenerated: true,
        sourceType: ScheduleSourceType.pet_birthday,
        sourcePetId: petId,
      );
    } else {
      await update(
        scheduleId: existing.id,
        title: title,
        scheduledAtMsec: birthdayMsec,
      );
    }
  }

  /// ペット削除時の cascade。auto schedule を soft delete。
  Future<void> deleteAutoSchedulesForPet(int petId) async {
    final ScheduleEntity? bday = await getAutoBirthdayForPet(petId);
    if (bday != null) {
      await softDelete(bday.id);
    }
  }
}

String? _emptyToNull(String? s) {
  if (s == null) return null;
  final String t = s.trim();
  return t.isEmpty ? null : t;
}

/// 月水金 → {1,3,5} → 0b0101010 = 42。値域外は無視。
int _encodeWeekdays(Set<int> weekdays) {
  int bits = 0;
  for (final int wd in weekdays) {
    if (wd >= 0 && wd <= 6) bits |= 1 << wd;
  }
  return bits;
}
