// ============================================================================
// petlo - Schedule Record Screen (build 5)
// ============================================================================
//
// 予定の新規/編集画面。
// 自動生成 (ペット birthday) の場合はバナーで表示、削除しても再生成される旨を案内。
//
// ============================================================================

import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/notifications/notification_permission_prompt.dart';
import '../../providers/notification_coordinator_provider.dart';
import '../../providers/pro_status_provider.dart';

import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_dimensions.dart';
import '../../../core/theme/app_typography.dart';
import '../../../core/utils/logger.dart';
import '../../../core/widgets/eyebrow_text.dart';
import '../../../core/widgets/primary_button.dart';
import '../../../core/widgets/section_label.dart';
import '../../../data/local/app_database.dart';
import '../../../data/local/database_enums.dart';
import '../../../data/repositories/schedules_repository.dart';
import '../../../l10n/generated/app_localizations.dart';
import '../../providers/pets_providers.dart';
import '../../providers/schedules_providers.dart';
import '../../providers/scope_providers.dart';
import '../../widgets/forms/date_field.dart';
import '../../widgets/forms/editorial_text_field.dart';
import '../../widgets/records/record_delete_helper.dart';

class ScheduleRecordScreen extends ConsumerStatefulWidget {
  const ScheduleRecordScreen({
    this.editingScheduleId,
    this.initialDate,
    super.key,
  });

  final int? editingScheduleId;

  /// 新規作成時の日付プリセット (カレンダー日付タップ時)
  final DateTime? initialDate;

  static Future<bool?> push(
    BuildContext context, {
    int? editingScheduleId,
    DateTime? initialDate,
  }) {
    return Navigator.of(context).push<bool>(
      MaterialPageRoute<bool>(
        builder: (_) => ScheduleRecordScreen(
          editingScheduleId: editingScheduleId,
          initialDate: initialDate,
        ),
      ),
    );
  }

  @override
  ConsumerState<ScheduleRecordScreen> createState() =>
      _ScheduleRecordScreenState();
}

class _ScheduleRecordScreenState
    extends ConsumerState<ScheduleRecordScreen> {
  final TextEditingController _titleC = TextEditingController();
  final TextEditingController _notesC = TextEditingController();

  bool _loaded = false;
  bool _isSubmitting = false;
  ScheduleEntity? _editing;

  ScheduleCategory _category = ScheduleCategory.custom;
  DateTime _date = DateTime.now();
  TimeOfDay? _time;
  ScheduleRecurrence _recurrence = ScheduleRecurrence.none;
  ScheduleNotificationTiming _notification =
      ScheduleNotificationTiming.none;
  Set<int> _selectedPetIds = <int>{};

  // build 47b (Scope B4): category=medication 時のみ表示する繰り返し通知
  // フィールド。HH:mm 文字列のリスト + 曜日 bitset (Set<int>)。
  // weekdays が空 = 毎日扱い (旧 medication_reminders と同じセマンティクス)。
  List<String> _times = <String>[];
  Set<int> _weekdays = <int>{};

  String? _titleError;

  @override
  void initState() {
    super.initState();
    if (widget.initialDate != null) {
      _date = widget.initialDate!;
    }
    if (widget.editingScheduleId != null) {
      Future<void>.microtask(_loadExisting);
    } else {
      _loaded = true;
    }
  }

  @override
  void dispose() {
    _titleC.dispose();
    _notesC.dispose();
    super.dispose();
  }

  Future<void> _loadExisting() async {
    try {
      final ScheduleEntity? s = await ref
          .read(schedulesRepositoryProvider)
          .getById(widget.editingScheduleId!);
      if (s == null) {
        if (mounted) Navigator.of(context).pop();
        return;
      }
      final DateTime dt = DateTime.fromMillisecondsSinceEpoch(s.scheduledAt);
      if (!mounted) return;
      setState(() {
        _editing = s;
        _titleC.text = s.title;
        _notesC.text = s.notes ?? '';
        _category = s.category;
        _date = dt;
        _time = s.hasTime ? TimeOfDay(hour: dt.hour, minute: dt.minute) : null;
        _recurrence = s.recurrence;
        _notification = s.notificationTiming;
        _selectedPetIds = s.relatedPetIds
            .map((String id) => int.tryParse(id))
            .whereType<int>()
            .toSet();
        // build 47b: medication 用 times/weekdays を復元
        _times = _decodeTimesJson(s.times);
        _weekdays = _decodeWeekdaysBits(s.weekdaysBits);
        _loaded = true;
      });
    } catch (e, st) {
      PetloLogger.instance.w('load schedule failed', error: e, stackTrace: st);
    }
  }

  bool get _isEditing => widget.editingScheduleId != null;
  bool get _isAutoGenerated => _editing?.isAutoGenerated ?? false;

  Future<void> _save() async {
    if (_isSubmitting) return;
    final String title = _titleC.text.trim();
    if (title.isEmpty) {
      setState(() => _titleError = AppLocalizations.of(context).common_input_invalid);
      return;
    }

    setState(() {
      _isSubmitting = true;
      _titleError = null;
    });

    try {
      final DateTime scheduled = _time == null
          ? DateTime(_date.year, _date.month, _date.day)
          : DateTime(_date.year, _date.month, _date.day, _time!.hour,
              _time!.minute);
      final int scheduledMs = scheduled.millisecondsSinceEpoch;

      final bool isMedication = _category == ScheduleCategory.medication;
      final SchedulesRepository repo = ref.read(schedulesRepositoryProvider);
      int? savedScheduleId;
      if (_isEditing) {
        await repo.update(
          scheduleId: widget.editingScheduleId!,
          title: title,
          category: _category,
          scheduledAtMsec: scheduledMs,
          hasTime: _time != null,
          recurrence: _recurrence,
          notificationTiming: _notification,
          notes: _notesC.text.trim(),
          relatedPetIds: _selectedPetIds.toList(),
          times: isMedication ? _times : null,
          weekdays: isMedication ? _weekdays : null,
          clearMedicationFields: !isMedication,
        );
        savedScheduleId = widget.editingScheduleId;
      } else {
        final String groupId = ref.read(currentGroupIdProvider);
        savedScheduleId = await repo.create(
          groupId: groupId,
          title: title,
          category: _category,
          scheduledAtMsec: scheduledMs,
          hasTime: _time != null,
          recurrence: _recurrence,
          notificationTiming: _notification,
          notes: _notesC.text.trim(),
          relatedPetIds: _selectedPetIds.toList(),
          times: isMedication ? _times : null,
          weekdays: isMedication ? _weekdays : null,
        );
      }

      // build 73: 保存後は 3 系統まとめて再割り当てする。
      // 個別 sync では総量 64 を守れないため (他系統の使用量が見えない)。
      if (savedScheduleId != null) {
        // build 73: 通知を期待した文脈で権限を要求する。
        // 未確定ならここで OS ダイアログ、拒否済みなら設定への導線。
        if (mounted) {
          await NotificationPermissionPrompt.ensureGranted(context);
        }
        await ref
            .read(notificationCoordinatorProvider)
            .rescheduleAll(isPro: ref.read(isProProvider));
      }

      if (!mounted) return;
      Navigator.of(context).pop(true);
    } catch (e, st) {
      PetloLogger.instance.w('save schedule failed', error: e, stackTrace: st);
      if (!mounted) return;
      setState(() => _isSubmitting = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content:
              Text(AppLocalizations.of(context).common_save_failed),
          behavior: SnackBarBehavior.floating,
        ),
      );
    }
  }

  Future<void> _delete() async {
    if (widget.editingScheduleId == null) return;
    final bool ok = await RecordDeleteHelper.confirm(context);
    if (!ok || !mounted) return;
    final bool deleted = await ref
        .read(schedulesRepositoryProvider)
        .softDelete(widget.editingScheduleId!);
    // build 73: 削除後も全体を再割り当てする。
    // 消えた分の枠が他系統に回るので、個別 cancel では不十分。
    if (deleted) {
      await ref
          .read(notificationCoordinatorProvider)
          .rescheduleAll(isPro: ref.read(isProProvider));
    }
    if (!mounted) return;
    if (deleted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(AppLocalizations.of(context).common_deleted),
          behavior: SnackBarBehavior.floating,
        ),
      );
      Navigator.of(context).pop(true);
    }
  }

  @override
  Widget build(BuildContext context) {
    final AppColors colors = AppColors.of(context);
    final AppTypography typo = AppTypography.of(context);
    final AppLocalizations l10n = AppLocalizations.of(context);

    if (!_loaded) {
      return Scaffold(
        backgroundColor: colors.bg,
        appBar: AppBar(backgroundColor: colors.bg, elevation: 0),
        body: const Center(child: CircularProgressIndicator()),
      );
    }

    return Scaffold(
      backgroundColor: colors.bg,
      appBar: AppBar(
        backgroundColor: colors.bg,
        foregroundColor: colors.fg,
        elevation: 0,
        scrolledUnderElevation: 0,
        title: Text(
          (_isEditing
                  ? l10n.schedule_appbar_edit
                  : l10n.schedule_appbar_new)
              .toUpperCase(),
          style: typo.metaSmall.copyWith(letterSpacing: 10 * 0.2),
        ),
        centerTitle: true,
        leading: TextButton(
          onPressed: () => Navigator.of(context).pop(false),
          child: Text(
            l10n.common_cancel.toUpperCase(),
            style: typo.metaSmall.copyWith(color: colors.fgMuted),
          ),
        ),
        leadingWidth: 80,
        actions: <Widget>[
          if (_isEditing)
            IconButton(
              icon: Icon(Icons.delete_outline,
                  color: colors.fgMuted, size: 22),
              onPressed: _delete,
              tooltip: l10n.common_delete,
            ),
        ],
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.fromLTRB(
            AppDimensions.paddingPage,
            AppDimensions.paddingPage,
            AppDimensions.paddingPage,
            AppDimensions.paddingPage * 2,
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              SectionLabel(
                l10n.schedule_list_eyebrow,
                size: EyebrowSize.large,
                padding: const EdgeInsets.fromLTRB(
                    0, 0, 0, AppDimensions.paddingSection),
              ),

              // 自動生成バナー
              if (_isAutoGenerated)
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(12),
                  margin: const EdgeInsets.only(
                      bottom: AppDimensions.gapXLarge),
                  decoration: BoxDecoration(
                    color: colors.bgSoft,
                    border: Border.all(color: colors.line),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Text(
                        l10n.schedule_auto_generated_label,
                        style: typo.bodyMedium
                            .copyWith(fontWeight: FontWeight.w600),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        l10n.schedule_auto_generated_helper,
                        style: typo.bodySmall
                            .copyWith(color: colors.fgMuted, height: 1.4),
                      ),
                    ],
                  ),
                ),

              // タイトル
              EditorialTextField(
                label: l10n.schedule_field_title,
                controller: _titleC,
                hint: l10n.schedule_field_title_hint,
                required: true,
                maxLength: 100,
                errorText: _titleError,
                onChanged: (_) {
                  if (_titleError != null) {
                    setState(() => _titleError = null);
                  }
                },
              ),
              const SizedBox(height: AppDimensions.gapXLarge),

              // 種類
              SectionLabel(l10n.schedule_field_category),
              const SizedBox(height: 8),
              _CategorySelector(
                value: _category,
                onChanged: (ScheduleCategory c) =>
                    setState(() => _category = c),
              ),
              const SizedBox(height: AppDimensions.paddingSection),

              // build 47b (Scope B4): category=medication 時のみ
              // times[] + weekdaysBits の入力 UI を出す。
              if (_category == ScheduleCategory.medication) ...<Widget>[
                _MedicationScheduleFields(
                  times: _times,
                  weekdays: _weekdays,
                  onTimesChanged: (List<String> t) =>
                      setState(() => _times = t),
                  onWeekdaysChanged: (Set<int> w) =>
                      setState(() => _weekdays = w),
                ),
                const SizedBox(height: AppDimensions.paddingSection),
              ],

              // 日付
              DateField(
                label: l10n.schedule_field_date,
                value: _date,
                required: true,
                firstDate: DateTime(DateTime.now().year - 5),
                lastDate: DateTime.now().add(const Duration(days: 365 * 10)),
                onChanged: (DateTime? d) {
                  if (d != null) setState(() => _date = d);
                },
              ),
              const SizedBox(height: AppDimensions.gapXLarge),

              // 時刻
              _TimeRow(
                value: _time,
                onChanged: (TimeOfDay? t) => setState(() => _time = t),
              ),
              const SizedBox(height: AppDimensions.paddingSection),

              // 繰り返し
              SectionLabel(l10n.schedule_field_recurrence),
              const SizedBox(height: 8),
              _RecurrenceSelector(
                value: _recurrence,
                onChanged: (ScheduleRecurrence r) =>
                    setState(() => _recurrence = r),
              ),
              const SizedBox(height: AppDimensions.paddingSection),

              // 通知
              SectionLabel(l10n.schedule_field_notification),
              const SizedBox(height: 8),
              _NotificationSelector(
                value: _notification,
                onChanged: (ScheduleNotificationTiming n) =>
                    setState(() => _notification = n),
              ),
              const SizedBox(height: AppDimensions.paddingSection),

              // メモ
              EditorialTextField(
                label: l10n.schedule_field_notes,
                controller: _notesC,
                hint: l10n.schedule_field_notes_hint,
                maxLines: 3,
                minLines: 2,
              ),
              const SizedBox(height: AppDimensions.paddingSection),

              // 関連ペット
              SectionLabel(l10n.schedule_field_pets),
              const SizedBox(height: 8),
              _RelatedPetsSelector(
                selected: _selectedPetIds,
                onChanged: (Set<int> ids) =>
                    setState(() => _selectedPetIds = ids),
              ),
              const SizedBox(height: AppDimensions.paddingSection * 1.5),

              PrimaryButton(
                label: _isSubmitting
                    ? l10n.common_saving
                    : (_isEditing ? l10n.common_update : l10n.common_save),
                onPressed: _isSubmitting ? null : _save,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// ============================================================================
class _CategorySelector extends StatelessWidget {
  const _CategorySelector({required this.value, required this.onChanged});

  final ScheduleCategory value;
  final ValueChanged<ScheduleCategory> onChanged;

  @override
  Widget build(BuildContext context) {
    final AppLocalizations l10n = AppLocalizations.of(context);
    return Wrap(
      spacing: 6,
      runSpacing: 6,
      children: <Widget>[
        for (final ScheduleCategory c in ScheduleCategory.values)
          _Chip(
            label: scheduleCategoryLabel(l10n, c),
            selected: value == c,
            onTap: () => onChanged(c),
          ),
      ],
    );
  }
}

class _RecurrenceSelector extends StatelessWidget {
  const _RecurrenceSelector({required this.value, required this.onChanged});

  final ScheduleRecurrence value;
  final ValueChanged<ScheduleRecurrence> onChanged;

  @override
  Widget build(BuildContext context) {
    final AppLocalizations l10n = AppLocalizations.of(context);
    return Wrap(
      spacing: 6,
      runSpacing: 6,
      children: <Widget>[
        for (final ScheduleRecurrence r in ScheduleRecurrence.values)
          _Chip(
            label: scheduleRecurrenceLabel(l10n, r),
            selected: value == r,
            onTap: () => onChanged(r),
          ),
      ],
    );
  }
}

class _NotificationSelector extends StatelessWidget {
  const _NotificationSelector(
      {required this.value, required this.onChanged});

  final ScheduleNotificationTiming value;
  final ValueChanged<ScheduleNotificationTiming> onChanged;

  @override
  Widget build(BuildContext context) {
    final AppLocalizations l10n = AppLocalizations.of(context);
    return Wrap(
      spacing: 6,
      runSpacing: 6,
      children: <Widget>[
        for (final ScheduleNotificationTiming n
            in ScheduleNotificationTiming.values)
          _Chip(
            label: scheduleNotificationLabel(l10n, n),
            selected: value == n,
            onTap: () => onChanged(n),
          ),
      ],
    );
  }
}

class _Chip extends StatelessWidget {
  const _Chip({
    required this.label,
    required this.selected,
    required this.onTap,
  });

  final String label;
  final bool selected;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final AppColors colors = AppColors.of(context);
    return InkWell(
      onTap: onTap,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 120),
        padding:
            const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        decoration: BoxDecoration(
          color: selected ? colors.fg : colors.bg,
          border: Border.all(color: colors.fg, width: 1),
        ),
        child: Text(
          label,
          style: TextStyle(
            fontFamily: 'Manrope',
            fontSize: 12,
            fontWeight:
                selected ? FontWeight.w700 : FontWeight.w500,
            color: selected ? colors.bg : colors.fg,
          ),
        ),
      ),
    );
  }
}

class _TimeRow extends StatelessWidget {
  const _TimeRow({required this.value, required this.onChanged});

  final TimeOfDay? value;
  final ValueChanged<TimeOfDay?> onChanged;

  @override
  Widget build(BuildContext context) {
    final AppColors colors = AppColors.of(context);
    final AppTypography typo = AppTypography.of(context);
    final AppLocalizations l10n = AppLocalizations.of(context);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        EyebrowText(l10n.schedule_field_time_optional),
        const SizedBox(height: AppDimensions.gapSmall),
        Row(
          children: <Widget>[
            Expanded(
              child: InkWell(
                onTap: () async {
                  final TimeOfDay? picked = await showTimePicker(
                    context: context,
                    initialTime: value ?? TimeOfDay.now(),
                  );
                  if (picked != null) onChanged(picked);
                },
                child: Container(
                  padding: const EdgeInsets.symmetric(vertical: 8),
                  decoration: BoxDecoration(
                    border: Border(
                      bottom: BorderSide(color: colors.line),
                    ),
                  ),
                  child: Text(
                    value == null
                        ? l10n.schedule_field_time_off
                        : value!.format(context),
                    style: typo.bodyLarge.copyWith(
                      color: value == null
                          ? colors.fgFaint
                          : colors.fg,
                    ),
                  ),
                ),
              ),
            ),
            if (value != null)
              IconButton(
                icon: Icon(Icons.close, size: 18, color: colors.fgMuted),
                onPressed: () => onChanged(null),
              ),
          ],
        ),
      ],
    );
  }
}

class _RelatedPetsSelector extends ConsumerWidget {
  const _RelatedPetsSelector(
      {required this.selected, required this.onChanged});

  final Set<int> selected;
  final ValueChanged<Set<int>> onChanged;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final AsyncValue<List<PetEntity>> petsAsync =
        ref.watch(currentGroupPetsProvider);
    final List<PetEntity> pets = petsAsync.maybeWhen(
      data: (List<PetEntity> l) => l,
      orElse: () => <PetEntity>[],
    );
    if (pets.isEmpty) return const SizedBox.shrink();
    return Wrap(
      spacing: 6,
      runSpacing: 6,
      children: <Widget>[
        for (final PetEntity p in pets)
          _Chip(
            label: p.name,
            selected: selected.contains(p.id),
            onTap: () {
              final Set<int> next = <int>{...selected};
              if (next.contains(p.id)) {
                next.remove(p.id);
              } else {
                next.add(p.id);
              }
              onChanged(next);
            },
          ),
      ],
    );
  }
}

// ============================================================================
// Helpers (公開 - 他画面でも再利用)
// ============================================================================

String scheduleCategoryLabel(
    AppLocalizations l10n, ScheduleCategory c) {
  switch (c) {
    case ScheduleCategory.vaccination:
      return l10n.schedule_category_vaccination;
    case ScheduleCategory.medication:
      return l10n.schedule_category_medication;
    case ScheduleCategory.visit:
      return l10n.schedule_category_visit;
    case ScheduleCategory.grooming:
      return l10n.schedule_category_grooming;
    case ScheduleCategory.meal:
      return l10n.schedule_category_meal;
    case ScheduleCategory.birthday:
      return l10n.schedule_category_birthday;
    case ScheduleCategory.memorial:
      return l10n.schedule_category_memorial;
    case ScheduleCategory.anniversary:
      return l10n.schedule_category_anniversary;
    case ScheduleCategory.custom:
      return l10n.schedule_category_custom;
    case ScheduleCategory.urgent:
      return l10n.schedule_category_urgent;
  }
}

String scheduleRecurrenceLabel(
    AppLocalizations l10n, ScheduleRecurrence r) {
  switch (r) {
    case ScheduleRecurrence.none:
      return l10n.schedule_recurrence_none;
    case ScheduleRecurrence.daily:
      return l10n.schedule_recurrence_daily;
    case ScheduleRecurrence.weekly:
      return l10n.schedule_recurrence_weekly;
    case ScheduleRecurrence.monthly:
      return l10n.schedule_recurrence_monthly;
    case ScheduleRecurrence.yearly:
      return l10n.schedule_recurrence_yearly;
  }
}

String scheduleNotificationLabel(
    AppLocalizations l10n, ScheduleNotificationTiming n) {
  switch (n) {
    case ScheduleNotificationTiming.none:
      return l10n.schedule_notification_none;
    case ScheduleNotificationTiming.on_day:
      return l10n.schedule_notification_on_day;
    case ScheduleNotificationTiming.day_before:
      return l10n.schedule_notification_day_before;
    case ScheduleNotificationTiming.week_before:
      return l10n.schedule_notification_week_before;
  }
}

/// カテゴリ → カラー(凡例の dot 色相当)
Color scheduleCategoryColor(AppColors colors, ScheduleCategory c) {
  switch (c) {
    case ScheduleCategory.urgent:
      return colors.accentDanger;
    case ScheduleCategory.vaccination:
    case ScheduleCategory.medication:
    case ScheduleCategory.visit:
      return colors.fg;
    case ScheduleCategory.grooming:
    case ScheduleCategory.meal:
    case ScheduleCategory.custom:
      return colors.fgMuted;
    case ScheduleCategory.birthday:
    case ScheduleCategory.memorial:
    case ScheduleCategory.anniversary:
      return colors.accentWarn;
  }
}

// ============================================================================
// _MedicationScheduleFields (build 47b, Scope B4)
// ============================================================================
//
// category=medication 時のみ表示される、毎日/曜日繰り返し用フィールド。
// 旧 medication_reminders フォームの UI を schedules フォームに統合した形。
//
//   - times: ["07:00","21:00"] の時刻チップ + 「+ 追加」アクション
//   - weekdays: 日〜土の bitset (空 = 毎日)
//
// ============================================================================
class _MedicationScheduleFields extends StatelessWidget {
  const _MedicationScheduleFields({
    required this.times,
    required this.weekdays,
    required this.onTimesChanged,
    required this.onWeekdaysChanged,
  });

  final List<String> times;
  final Set<int> weekdays;
  final ValueChanged<List<String>> onTimesChanged;
  final ValueChanged<Set<int>> onWeekdaysChanged;

  static List<String> _weekdayShortLabels(BuildContext context) {
    final String locale = Localizations.localeOf(context).languageCode;
    if (locale == 'ja') {
      return const <String>['日', '月', '火', '水', '木', '金', '土'];
    }
    if (locale == 'zh') {
      return const <String>['日', '一', '二', '三', '四', '五', '六'];
    }
    return const <String>['S', 'M', 'T', 'W', 'T', 'F', 'S'];
  }

  Future<void> _addTime(BuildContext context) async {
    final TimeOfDay? picked = await showTimePicker(
      context: context,
      initialTime: const TimeOfDay(hour: 8, minute: 0),
    );
    if (picked == null) return;
    final String hhmm =
        '${picked.hour.toString().padLeft(2, '0')}:${picked.minute.toString().padLeft(2, '0')}';
    if (times.contains(hhmm)) return; // 重複は無視
    final List<String> next = <String>[...times, hhmm]..sort();
    onTimesChanged(next);
  }

  void _removeTime(String t) {
    final List<String> next = <String>[...times]..remove(t);
    onTimesChanged(next);
  }

  void _toggleWeekday(int wd) {
    final Set<int> next = <int>{...weekdays};
    if (next.contains(wd)) {
      next.remove(wd);
    } else {
      next.add(wd);
    }
    onWeekdaysChanged(next);
  }

  @override
  Widget build(BuildContext context) {
    final AppColors colors = AppColors.of(context);
    final AppTypography typo = AppTypography.of(context);
    final AppLocalizations l10n = AppLocalizations.of(context);
    final List<String> wdLabels = _weekdayShortLabels(context);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        SectionLabel(l10n.schedule_medication_times_label),
        const SizedBox(height: 8),
        Wrap(
          spacing: 6,
          runSpacing: 6,
          children: <Widget>[
            for (final String t in times)
              InputChip(
                label: Text(
                  t,
                  style: const TextStyle(
                    fontFamily: 'JetBrainsMono',
                    fontFeatures: <FontFeature>[
                      FontFeature.tabularFigures(),
                    ],
                  ),
                ),
                onDeleted: () => _removeTime(t),
                backgroundColor: colors.bgSoft,
                deleteIconColor: colors.fgMuted,
                side: BorderSide(color: colors.line),
              ),
            ActionChip(
              label: Text('+ ${l10n.schedule_medication_add_time}'),
              onPressed: () => _addTime(context),
              backgroundColor: colors.bg,
              side: BorderSide(color: colors.fg),
            ),
          ],
        ),
        const SizedBox(height: 4),
        Text(
          l10n.schedule_medication_times_hint,
          style: typo.bodySmall.copyWith(color: colors.fgMuted),
        ),
        const SizedBox(height: 16),

        SectionLabel(l10n.schedule_medication_weekdays_label),
        const SizedBox(height: 8),
        Wrap(
          spacing: 6,
          runSpacing: 6,
          children: <Widget>[
            for (int wd = 0; wd < 7; wd++)
              FilterChip(
                label: Text(wdLabels[wd]),
                selected: weekdays.contains(wd),
                onSelected: (_) => _toggleWeekday(wd),
                backgroundColor: colors.bg,
                selectedColor: colors.fg,
                showCheckmark: false,
                labelStyle: typo.bodySmall.copyWith(
                  color: weekdays.contains(wd) ? colors.bg : colors.fg,
                  fontWeight: FontWeight.w600,
                ),
                side: BorderSide(color: colors.line),
              ),
          ],
        ),
        const SizedBox(height: 4),
        Text(
          l10n.schedule_medication_weekdays_hint,
          style: typo.bodySmall.copyWith(color: colors.fgMuted),
        ),
      ],
    );
  }
}

// ============================================================================
// build 47b helpers: schedules.times / weekdaysBits の decode (UI 側)
// ============================================================================

List<String> _decodeTimesJson(String? raw) {
  if (raw == null || raw.isEmpty) return <String>[];
  try {
    final dynamic decoded = jsonDecode(raw);
    if (decoded is List) {
      return decoded.whereType<String>().toList();
    }
  } catch (_) {
    // ignore
  }
  return <String>[];
}

Set<int> _decodeWeekdaysBits(int? bits) {
  if (bits == null || bits == 0) return <int>{};
  final Set<int> out = <int>{};
  for (int i = 0; i < 7; i++) {
    if ((bits & (1 << i)) != 0) out.add(i);
  }
  return out;
}
