// ============================================================================
// petlo - Schedules Table
// ============================================================================
//
// 予定 (build 5)。
// ペットの誕生日、ワクチン、通院、トリミング等を1テーブルに集約。
//
// rev3 §予定: ペット中心のカレンダー機能の基盤。
//
// ============================================================================

import 'package:drift/drift.dart';

import '../database_converters.dart';
import '../database_enums.dart';

@DataClassName('ScheduleEntity')
class Schedules extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get remoteId => text().nullable()();
  TextColumn get groupId => text().withDefault(const Constant('personal'))();

  /// タイトル(例: 狂犬病ワクチン、トリミング、Aの誕生日)
  TextColumn get title => text().withLength(min: 1, max: 200)();

  /// 種類
  TextColumn get category =>
      text().map(const AppEnumConverter(ScheduleCategory.values))();

  /// 予定日(UTC ms)
  IntColumn get scheduledAt => integer()();

  /// 時刻が指定されているか(false なら終日扱い)
  BoolColumn get hasTime => boolean().withDefault(const Constant(false))();

  /// 繰り返しパターン
  TextColumn get recurrence => text()
      .map(const AppEnumConverter(ScheduleRecurrence.values))
      .withDefault(const Constant('none'))();

  /// 通知タイミング(UI のみ、実 Push は v1.1)
  TextColumn get notificationTiming => text()
      .map(const AppEnumConverter(ScheduleNotificationTiming.values))
      .withDefault(const Constant('none'))();

  /// メモ
  TextColumn get notes => text().nullable()();

  /// 関連するペット ID(複数可、JSON 配列文字列)
  /// 空の場合はグループ全体の予定として扱う。
  TextColumn get relatedPetIds =>
      text().map(const StringListConverter()).withDefault(const Constant('[]'))();

  // ============================================================================
  // build 47b (Scope B1): 投薬リマインダー統合用カラム
  // ============================================================================
  // category=medication 時のみ意味を持つ。他カテゴリでは null。
  // 旧 medication_reminders.times / weekdays_bits をそのまま吸収する設計。
  //
  // times: ["07:00","21:00"] のような時刻 JSON 配列文字列。null = 未設定
  //   (= 通知なしの単点 schedule)。
  // weekdaysBits: 月水金 → {1,3,5} の bitset を int として保存。null か 0
  //   = 毎日。値は WeekdaysBitsetConverter (medication_reminders と同一) を
  //   使う想定だが、ここでは raw int として保持し、変換は repository/UI 側で
  //   行う (drift converter は Set<int> ⇔ int の往復で扱う際に存在チェックが
  //   面倒なので nullable int でフラットに持つ)。

  /// 通知時刻のリスト (HH:mm の JSON 配列、例: ["07:00","21:00"])。
  /// category=medication 時のみ使用。null なら schedule は通知時刻列を持たず、
  /// 通常の scheduledAt + notificationTiming で発火する。
  TextColumn get times => text().nullable()();

  /// 通知曜日 bitset (月水金 → 2 + 8 + 32 = 42 など)。null か 0 = 毎日。
  /// category=medication 時のみ使用。
  IntColumn get weekdaysBits => integer().nullable()();

  /// 自動生成かどうか
  /// true: ペット誕生日等から生成。手動編集も可能だが、
  /// ソースが変わると(ペット birthday 変更等)更新される。
  BoolColumn get isAutoGenerated => boolean().withDefault(const Constant(false))();

  /// 自動生成のソース種別
  TextColumn get sourceType => text()
      .map(const AppEnumConverter(ScheduleSourceType.values))
      .withDefault(const Constant('manual'))();

  /// 自動生成元のペット ID(birthday 自動 schedule で使用)
  IntColumn get sourcePetId => integer().nullable()();

  TextColumn get createdBy => text().nullable()();
  TextColumn get syncStatus => text()
      .map(const AppEnumConverter(SyncStatus.values))
      .withDefault(const Constant('synced'))();
  IntColumn get deletedAt => integer().nullable()();
  IntColumn get createdAt => integer()();
  IntColumn get updatedAt => integer()();
  IntColumn get lastModifiedAtClient => integer().nullable()();
}
